spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost
    username: admin
    password: admin

  h2:
    console:
      enabled: true
  jackson.deserialization.fail-on-unknown-properties: true

logging.level.root: off